name: Testing Comp348 assignment

on:
   push:
   workflow_dispatch:
     
jobs:
  testing-assignment-output:
    runs-on: ubuntu-latest
    container:
      image: hsinghineat/harrypipeline
    steps:
      - name: copying the code from the repository
        uses: actions/checkout@v3
      - name: running the code
        run: |
          ls -all
          gcc report.c replace.c traversal.c text.c
          a lorem
